name: main

on: [push]

jobs:
  test-on-sqlite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.4
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load dependency cache
        id: dependency-cache
        uses: actions/cache@v2
        with:
          path: .venv/
          key: venv-v0-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies
        if: steps.dependency-cache.outputs.cache-hit != 'true'
        run: poetry install --no-interaction

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest --cov=resql/ --cov-report=xml tests/

      # move to https://github.com/codecov/codecov-action in the future
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage.xml
          path: coverage.xml

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.4
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load dependency cache
        id: dependency-cache
        uses: actions/cache@v2
        with:
          path: .venv/
          key: venv-v0-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies
        if: steps.dependency-cache.outputs.cache-hit != 'true'
        run: poetry install --no-interaction

      - name: Black
        run: |
          source .venv/bin/activate
          black --check examples/ resql/ tests/

      - name: Mypy
        run: |
          source .venv/bin/activate
          mypy examples/ resql/ tests/

      - name: Pylint
        run: |
          source .venv/bin/activate
          pylint examples/ resql/ tests/
